In [1]:
from pathlib import Path
import geopandas as gpd

In [2]:
data = Path("../data/shapefiles/nts_snrc_250k_yk_selection.shp")
grid = gpd.read_file(data)
grid.head()

,NTS_SNRC,NAME_ENG,NOM_FRA,SRID,SHAPE_AREA,SHAPE_LEN,geometry
0,115C,None,None,6,2.0,6.0,"POLYGON ((-140.00000 60.00000, -140.01667 60.0..."
1,115F,None,None,6,2.0,6.0,"POLYGON ((-140.00000 61.00000, -140.01667 61.0..."
2,115G,KLUANE LAKE,KLUANE LAKE,6,2.0,6.0,"POLYGON ((-139.98333 61.00000, -140.00000 61.0..."
3,105K,TAY RIVER,TAY RIVER,6,2.0,6.0,"POLYGON ((-133.98333 62.00000, -134.00000 62.0..."
4,105L,GLENLYON LAKE,GLENLYON LAKE,6,2.0,6.0,"POLYGON ((-135.98333 62.00000, -136.00000 62.0..."

In [3]:
grid['ft'] = 0
grid['ta'] = 0

In [4]:
grid

,NTS_SNRC,NAME_ENG,NOM_FRA,SRID,SHAPE_AREA,SHAPE_LEN,geometry,ft,ta
0,115C,None,None,6,2.0,6.0,"POLYGON ((-140.00000 60.00000, -140.01667 60.0...",0,0
1,115F,None,None,6,2.0,6.0,"POLYGON ((-140.00000 61.00000, -140.01667 61.0...",0,0
2,115G,KLUANE LAKE,KLUANE LAKE,6,2.0,6.0,"POLYGON ((-139.98333 61.00000, -140.00000 61.0...",0,0
3,105K,TAY RIVER,TAY RIVER,6,2.0,6.0,"POLYGON ((-133.98333 62.00000, -134.00000 62.0...",0,0
4,105L,GLENLYON LAKE,GLENLYON LAKE,6,2.0,6.0,"POLYGON ((-135.98333 62.00000, -136.00000 62.0...",0,0
...,...,...,...,...,...,...,...,...,...
58,116P,BELL RIVER,BELL RIVER,6,2.0,6.0,"POLYGON ((-137.98333 67.00000, -138.00000 67.0...",0,0
59,117A,BLOW RIVER,BLOW RIVER,6,4.0,10.0,"POLYGON ((-139.98333 68.00000, -140.00000 68.0...",0,0
60,117B,DAVIDSON MOUNTAINS,DAVIDSON MOUNTAINS,6,2.0,6.0,"POLYGON ((-141.98333 68.00000, -142.00000 68.0...",0,0
61,117C,BACKHOUSE RIVER,BACKHOUSE RIVER,6,2.0,6.0,"POLYGON ((-141.98333 69.00000, -142.00000 69.0...",0,0
62,117D,HERSCHEL ISLAND,HERSCHEL ISLAND,6,4.0,10.0,"POLYGON ((-139.98333 69.00000, -140.00000 69.0...",0,0

In [5]:
grid.to_file("../data/shapefiles/grid.shp")